sudo: false
language: node_js
node_js:
  - '10.16.0'
script:
  - pnpm run build && pnpm run lint && pnpm recursive run test-ci
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | PNPM_VERSION=3.5.3 node
install:
  - pnpm install && pnpm recursive install
cache:
  directories:
    - /home/travis/.pnpm-store
branches:
  only:
    - master
